version: "3.9"

services:
  api:
    build: .
    container_name: nest_bankaccount_api
    ports:
      - "3333:3333"
    volumes:
      - .:/home/node/nest
    depends_on:
      - "rabbitmq"

  rabbitmq:
    image: "rabbitmq:3.8-management-alpine"
    container_name: nest_msg_rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq/mnesia
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    

volumes:
  postgres:
    driver: local
  rabbitmq:
    driver: local

networks:
  default:
    name: nest_msg_network
