services:
  api:
    build: .
    container_name: nest_bankaccount_api
    ports:
      - "3333:3333"
    volumes:
      - .:/home/node/nest 
    depends_on:
      - "rabbitmq"
      - "mysql"

  rabbitmq:
    image: "rabbitmq:3.8-management-alpine"
    container_name: nest_msg_rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq/mnesia
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "300m"

  mysql:
    image: "mysql:8.0"
    container_name: nest_msg_mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=EFEbank
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - default

volumes:
  postgres:
    driver: local
  rabbitmq:
    driver: local
  mysql:
    driver: local

networks:
  default:
    name: nest_msg_network
